services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: results-validator-db # use specific name to reduce flyway conflicts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  wiremock:
    image: wiremock/wiremock:3.13.0
    ports:
      - "8082:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - wiremock
    environment:
      APP_NAME_DATASOURCE_URL: jdbc:postgresql://db:5432/results-validator-db
      APP_NAME_DATASOURCE_USERNAME: postgres
      APP_NAME_DATASOURCE_PASSWORD: postgres
      AUTHZ_ENABLED: "true"
      CP_BASE_URL: "http://wiremock:8080"
    ports:
      - "4550:4550"

